### ISSUE TITLE
Problema generazione documentazione Doxygen

### ISSUE THREAD

**Issue by palberoni** [ARPA-SIMC/radarlib#1]
La documentazione di alcuni moduli non viene generata.  Vedi log file allegato.
[log.zip](https://github.com/ARPA-SIMC/radarlib/files/311874/log.zip)

**Comment by edigiacomo** [comment]
Ho provato a lanciare la generazione della documentazione su due sistemi diversi (Fedora 20 e Debian 8) senza grossi problemi. Ad esempio, il tuo primo messaggi di log:

```
/ponte/rad_svn/radarlib.git/trunk/radarlib/odimh5v20_metadata.cpp:423: warning: File ended in the middle of a comment block! Perhaps a missing \endcode?
```

Diventa:

```
Preprocessing /autofs/nethomes/edigiacomo/src/radarlib/radarlib/odimh5v20_metadata.cpp...
Parsing file /autofs/nethomes/edigiacomo/src/radarlib/radarlib/odimh5v20_metadata.cpp...
```

Ti chiedo dunque alcune cose:
1. Sei sicuro di avere una working copy pulita e senza modifiche locali (`svn status` oppure `git status`, a seconda del controllo di versione che stai usando  ti possono dare conferma)? Nel caso in cui tu abbia modifiche locali, le puoi committare?
2. Come lanci la generazione della documentazione? Puoi provare con un `make clean -C doc && make -C doc` dalla radice del progetto?
3. Quali classi non riesci a visualizzare (mi bastano alcuni esempi)?

**Comment by palberoni** [comment]
1) ho verificato, utilizzo una versione non moficata.

2) fatto, ma il risultato non cambia

3) ad esempio una qualsiasi di quelle definite in odimh5v21_support.hpp
