### ISSUE TITLE
[fedora 34] error: ISO C++17 does not allow dynamic exception specifications

### ISSUE THREAD

**Issue by brancomat** [ARPA-SIMC/radarlib#3]
Fedora 34 builds are failing because of the aforementioned error.

Full log:
https://download.copr.fedorainfracloud.org/results/simc/stable/fedora-34-x86_64/02177101-radarlib/builder-live.log.gz

https://simc.arpae.it/moncic-ci/radarlib/202105101525/master/fedora34/build.log

**Comment by edigiacomo** [comment]
If I understand correctly, the C++ guidelines discourages the use of exception specifications https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md#Re-specifications.

Then, we can simply remove the `throw(....)` from the class declarations.
